version: "3"

services:
  browser:
    image: selenium/standalone-chrome
    ports:
      - "8080:8080"
      - "7900:7900"
    healthcheck:
      test: "curl http://localhost:4444"
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build: .
    depends_on:
      browser:
        condition: service_healthy